services:
  mautrix-telegram:
    environment:
      VIRTUAL_PORT: ${VIRTUAL_PORT:-29317}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PROTO: ${VIRTUAL_PROTO:-https}
    volumes:
      - step-ca-certs:/certs
    networks:
      - step-ca-network

volumes:
  step-ca-certs:
    name: step-ca-certs
    external: true

networks:
  step-ca-network:
    external: true
